services:
  webapps:
    image: webapps
    container_name: webapps
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - webapps-network
    volumes:
      - ./:/var/www/html
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    container_name: webapps_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: webapps
      MYSQL_USER: webapps
      MYSQL_PASSWORD: webapps
      MYSQL_ROOT_PASSWORD: webapps
    networks:
      - webapps-network
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  selenium:
    image: selenium/standalone-chrome
    container_name: webapps_selenium
    ports:
      - "7900:7900" # VNC (pra ver o browser rodando)
    networks:
      - webapps-network
    shm_size: 2gb

  senhaunica-faker:
    image: uspdev/senhaunica-faker
    container_name: webapps_senhaunica-faker
    ports:
      - "3141:3141"
    environment:
          - APP_URL=http://auth.local:3141
    networks:
      webapps-network:
        aliases:
          - auth.local

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: webapps_phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: webapps
    networks:
      - webapps-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: webapps__mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Interface Web
    networks:
      - webapps-network

  gwmariadb:
    image: ghcr.io/fflch/gwmariadb:latest
    container_name: webapps_gwmariadb
    depends_on:
      - mariadb
    networks:
      - webapps-network
    environment:
      TOKEN: 123
      DB_HOST: mariadb
      DB_NAME: admin
      DB_USER: admin
      DB_PASS: admin
      DB_PORT: 3306

networks:
  webapps-network: